//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthorization.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomersID { get; set; }
        public string SurName { get; set; }
        public string Full_Name { get; set; }
        public string Email { get; set; }
        public string DOJ { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
    }
}
