//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthorization.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int RegId { get; set; }
        public string StudentId { get; set; }
        public string StdFirstName { get; set; }
        public string StdLastName { get; set; }
        public string StdPassword { get; set; }
        public string StdEmail { get; set; }
        public decimal StdMobile { get; set; }
        public string StdAddress { get; set; }
        public int StdGender { get; set; }
        public System.DateTime StdDateOfBirth { get; set; }
        public int StdState { get; set; }
        public int StdCountry { get; set; }
        public string StdProfilePic { get; set; }
        public System.DateTime StdCreatedDate { get; set; }
        public System.DateTime StdRegisteredDate { get; set; }
    
        public virtual tbl_Gender_Master tbl_Gender_Master { get; set; }
    }
}
