//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthorization.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Customers_M
    {
        public int Id { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string TITLE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string District { get; set; }
        public string REGION { get; set; }
        public string GST_STATE_NAME { get; set; }
        public string GST_Tin_Number { get; set; }
        public string REGION_DESC { get; set; }
        public string POSTAL_CODE { get; set; }
        public string GST_NUMBER { get; set; }
        public string PAN_NO { get; set; }
        public string Segment_Name { get; set; }
        public string Sales_Office { get; set; }
        public string HQCODE { get; set; }
        public string HQNAME { get; set; }
        public string Moblie_No { get; set; }
        public string EmailId { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    }
}
