//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthorization.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_StudentInfo
    {
        public int ID { get; set; }
        public string StudentId { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Address { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<decimal> ContactMobile { get; set; }
        public string AdditionalComments { get; set; }
        public Nullable<bool> IsResgistered { get; set; }
        public Nullable<System.DateTime> ResgisteredDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> PasswordGenerated { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
