//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAuthorization.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public int tblCustomersID { get; set; }
        public Nullable<System.Guid> Id { get; set; }
        public string SurName { get; set; }
        public string UserName { get; set; }
        public string EmailId { get; set; }
        public string DOB { get; set; }
        public string DOJ { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    }
}
